language: node_js

node_js:
  - '0.10'

notifications:
  email:
    smcarthur@mozilla.com
  irc:
    channels:
      - 'irc.mozilla.org#fxa'
    use_notice: false
    skip_join: false

env:
  - NODE_ENV=test DB=memory
